version: '3.8'

services:
  kaggle-setup:
    container_name: kaggle_cli_test
    image: python:3.11
    user: root
    volumes:
      - ~/.kaggle:/root/.kaggle:ro
    working_dir: /app
    command:
      - bash
      - -c
      - |
        set -e
        echo "Installing kaggle CLI..."
        pip install kaggle > /dev/null

        echo "Testing kaggle auth..."
        kaggle datasets list --max-results 5
        echo "Kaggle CLI is set up and authenticated successfully."
